### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by jchen9314** [UBC-MDS/prepackPy#29]
- [x] address feedback from TA 
- [x] pass all test cases and reach 100% test coverage
- [x] update package README (a screenshot of test coverage report)
- [x] use GitHub's issue tracker and milestone feature to plan the milestone (document tasks in issues and assign each issue to Milestone 3).

**Comment by smwatts** [comment]
I'll add in the `import numpy as np` to all the examples re: TA feedback once everything is merged. I can also add the screenshots to the repos.

**Comment by jchen9314** [comment]
Thanks, Sarah.
